version: "3.7"
services:
  python_app:
    image: 
  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/prometheus/prometheus.yml'
      - '--storage/tsdb.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
    ports:
      - 9090:9090
    depends_on:
      - alertmanager
    restart: always
    networks:
      - prometheus_net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: monitoring_alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager/
      - ./data/alertmanager:/alertmanager
    command:
      - '--config.file=/prometheus/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093
    networks:
      - prometheus_net
  
  node:
    image: prom/node-exporter:latest
    contianer_name: monitoring_node_exporter
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/rootfs:ro'
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    restart: always
    networks:
      - prometheus_net
  
  cadvisor:
    image: google/cadvisor
    contianer_name: monitoring_cadvisor
    ports:
      - 8000:8080
    volumes:
      - /:/root/fs:ro
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker
    netowrks:
      - prometheus_net

  grafana:
    image: grafana/grafana-oss:latest
    container_name: monitoring_grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/etc/grafana/
    environment:
      - ADMIN_PSWD=grafana
      - USR_SIGNUP=false
